version: "3.9"
services:
  web:
    build: .
    container_name: bowlsace_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      TZ: UTC
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
    user: nobody
    depends_on:
      db:
        condition: service_healthy
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/startup.sh"]
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "production"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  db:
    image: postgres:14
    container_name: bowlsace_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: UTC
      PGDATA: /var/lib/postgresql/data/pgdata
    security_opt:
      - no-new-privileges:true
    user: postgres
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "production"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  default:
    name: bowlsace_network

volumes:
  postgres_data:
    name: bowlsace_postgres_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgres
